src/gearo/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/social/login/cancelled/$', views.gearouser.FacebookLoginCancelledView.as_view(),
        name='socialaccount_login_cancelled'),
    url(r'^accounts/social/login/error/$', views.gearouser.FacebookLoginErrorView.as_view(),
        name='socialaccount_login_error'),
    url(r'^accounts/social/login/confirm/(?P<token>.*)/$', views.gearouser.FacebookConfirmAuthentication.as_view(),
        name='socialaccount_login_confirmation'),
    url(r'^$', views.index_view, name='index'),  
    url(r'^registrieren/$', views.gearouser.RegisterView.as_view(), name='register'),
    url(r'^login/$', views.gearouser.LoginView.as_view(), name='login'),
    url(r'^mail-bestaetigen/(?P<token>.*)/$', views.gearouser.ConfirmMailView.as_view(), name='confirmmail'),
    url(r'^passwort-zuruecksetzen/$', views.gearouser.ResetPasswordView.as_view(), name='resetpassword'),
    url(r'^passwort-zuruecksetzen/(?P<token>.*)/$', views.gearouser.ResetPasswordConfirmView.as_view(), name='resetpasswordconfirm'),
    url(r'^abmelden/$', views.gearouser.LogoutView.as_view(), name='logout'),
    url(r'^inserieren/$', views.advertisements.AdvertisementCreateView.as_view(), name='advertise'),
    url(r'^posteingang/$', views.chatsystem.PostboxView.as_view(), name='postbox'),
    url(r'^posteingang/anfrage/(?P<inqid>[0-9]+)/$', views.chatsystem.ManageInquiryView.as_view(), name='maninq'),
    url(r'^posteingang/buchung/(?P<inqid>[0-9]+)/$',  views.chatsystem.InquiryDetailView.as_view(), name='showinq'),
    url(r'^posteingang/buchung/(?P<inqid>[0-9]+)/stornieren/$',  views.chatsystem.CancelInquiryView.as_view(), name='cancel'),
    url(r'^posteingang/buchung/(?P<inqid>[0-9]+)/uebergabe-protokoll/$',  views.chatsystem.HandingOverProtocolView.as_view(), name='handingover'),
    url(r'^posteingang/buchung/(?P<inqid>[0-9]+)/rueckgabe-protokoll/$',  views.chatsystem.ReturnProtocolView.as_view(), name='returnproto'),
    url(r'^posteingang/buchung/(?P<inqid>[0-9]+)/rechnung-stellen/$',  views.bills.GenerateInvoiceView.as_view(), name='geninvoice'),
    url(r'^posteingang/buchung/(?P<inqid>[0-9]+)/abschliessen/$', views.chatsystem.CompleteInquiryView.as_view(), name='completeinq'),
    url(r'^posteingang/buchung/(?P<inqid>[0-9]+)/annehmen/$', views.chatsystem.AcceptLessorView.as_view(), name='acceptlessor'),
    url(r'^posteingang/buchung/(?P<inqid>[0-9]+)/ablehnen/$', views.chatsystem.RejectLessorView.as_view(), name='rejectlessor'),
    
    url(r'^posteingang/buchung/(?P<inqid>[0-9]+)/bewerten/super/(?P<token>.*)/$', views.reviews.UserReviewView.as_view(rating='great'), name='reviewgreat'),
    url(r'^posteingang/buchung/(?P<inqid>[0-9]+)/bewerten/inordnung/(?P<token>.*)/$', views.reviews.UserReviewView.as_view(rating='alright'), name='reviewalright'),
    url(r'^posteingang/buchung/(?P<inqid>[0-9]+)/bewerten/ginggarnicht/(?P<token>.*)/$', views.reviews.UserReviewView.as_view(rating='nogo'), name='reviewnogo'),

    url(r'^profil/bearbeiten/$', views.account.ProfileUpdateView.as_view(), name='profile_edit'),
    url(r'^personliche-info/bearbeiten/$', views.account.PersonalInfoUpdateView.as_view(), name='personal_info_edit'),
    url(r'^kontaktdaten/bearbeiten/$', views.account.ContactInfoView.as_view(), name='contact_info_edit'),
    url(r'^identitat/bearbeiten/$', views.account.IdentificationInfoUpdateView.as_view(), name='identification_info_edit'),
    url(r'^adress-rechnungs-info/bearbeiten/$', views.account.AddressInfoUpdateView.as_view(), name='address_info_edit'),
    url(r'^bankinformationen/bearbeiten/$', views.account.BankInfoUpdateView.as_view(), name='bank_info_edit'),
    url(r'^meine-rechnungen/$', views.bills.BillsApplicantView.as_view(), name='mybills'),
    url(r'^email/andern/$', views.account.EmailChangeView.as_view(), name='change_email'),
    url(r'^passwort/andern/$', views.account.PasswordChangeView.as_view(), name='change_password'),

    url(r'^chat/(?P<slug>\w+)/(?P<trans_id>[0-9]+)/$', views.chatsystem.ChatroomView.as_view(), name='chat'),
    url(r'^profil/check/mail/$', views.gearouser.MailCheckView.as_view(), name='mailcheck'),
    url(r'^profil/bearbeiten/verify-phone-number/send/$', views.gearouser.SendPhoneVerificationView.as_view(), name='send_phone_verification'),
    url(r'^profil/bearbeiten/verify-phone-number/check/$', views.gearouser.CheckPhoneVerificationView.as_view(), name='check_phone_verification'),
    url(r'^profil/bearbeiten/uploadavatar/$', views.gearouser.UploadAvatarView.as_view(), name='uploadavatar'),
    url(r'^profil/bearbeiten/cropavatar/$', views.gearouser.CropAvatarView.as_view(), name='cropavatar'),
    url(r'^profil/(?P<username>[-_\w]+)/$', views.gearouser.UserProfileView.as_view(), name='publicprofil'),
    url(r'^profil/(?P<username>[-_\w]+)/bewertungen/$', views.gearouser.UserProfileReviewsView.as_view(), name='userdetailreviews'),
    url(r'^account/accept-terms/$', views.gearouser.AcceptTermsView.as_view(), name='accept_terms'),

    url(r'^meine-rechnungen/$', views.bills.BillsApplicantView.as_view(), name='mybills'),
    url(r'^meine-rechnungen/anmietungen/$', views.bills.BillsApplicantView.as_view(), name='mybillsapp'),
    url(r'^meine-rechnungen/vermietungen/$', views.bills.BillsLessorView.as_view(), name='mybillsles'),
    url(r'^meine-rechnungen/getbill/(?P<billid>[0-9]+)/$', views.bills.GetBillView.as_view(), name='renderpdf'),
    
    url(r'^faq/$', views.faq.FAQView.as_view(), name='faq'),
    
    url(r'^(?P<attachment_type>[-_\w]+)/upload/$', views.imageupload.UploadAttachmentView.as_view(), name='imageupload'),
    url(r'^(?P<attachment_type>[-_\w]+)/upload/crop/$', views.imageupload.CropAttachmentView.as_view(), name='imagecrop'),
    url(r'^(?P<attachment_type>[-_\w]+)/upload/delete/$', views.imageupload.AttachmentDeleteView.as_view(), name='uploaddelete'),

    url(r'^suchen/$', views.search.SearchRedirectView.as_view(), name='search_redirect'),
    url(r'^suche/$', views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/ort/(?P<place>[%-_\w\0-9]+)/start/(?P<pickup>[%-_\w\0-9]+)/ende/(?P<return>[%-_\w\0-9]+)/radius/(?P<distance>[\d]+)km/$',
        views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/ort/(?P<place>[%-_\w\0-9]+)/start/(?P<pickup>[%-_\w\0-9]+)/ende/(?P<return>[%-_\w\0-9]+)/$',
        views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/ort/(?P<place>[%-_\w\0-9]+)/tag/(?P<day>[%-_\w\0-9]+)/radius/(?P<distance>[\d]+)km/$',
        views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/ort/(?P<place>[%-_\w\0-9]+)/tag/(?P<day>[%-_\w\0-9]+)/$',
        views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/(?P<term>[%-_\w\0-9]+)/ort/(?P<place>[%-_\w\0-9]+)/start/(?P<pickup>[%-_\w\0-9]+)/ende/(?P<return>[%-_\w\0-9]+)/radius/(?P<distance>[\d]+)km/$',
        views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/(?P<term>[%-_\w\0-9]+)/ort/(?P<place>[%-_\w\0-9]+)/start/(?P<pickup>[%-_\w\0-9]+)/ende/(?P<return>[%-_\w\0-9]+)/$',
        views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/(?P<term>[%-_\w\0-9]+)/start/(?P<pickup>[%-_\w\0-9]+)/ende/(?P<return>[%-_\w\0-9]+)/$',
        views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/(?P<term>[%-_\w\0-9]+)/ort/(?P<place>[%-_\w\0-9]+)/tag/(?P<day>[%-_\w\0-9]+)/radius/(?P<distance>[\d]+)km/$',
        views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/(?P<term>[%-_\w\0-9]+)/ort/(?P<place>[%-_\w\0-9]+)/tag/(?P<day>[%-_\w\0-9]+)/$',
        views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/(?P<term>[%-_\w\0-9]+)/tag/(?P<day>[%-_\w\0-9]+)/$',
        views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/(?P<term>[%-_\w\0-9]+)/ort/(?P<place>[%-_\w\0-9]+)/radius/(?P<distance>[\d]+)km/$',
        views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/(?P<term>[%-_\w\0-9]+)/ort/(?P<place>[%-_\w\0-9]+)/$',
        views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/ort/(?P<place>[%-_\w\0-9]+)/radius/(?P<distance>[\d]+)km/$',
        views.search.SearchResultsView.as_view(), name='search_results'),

    url(r'^suche/kategorie/(?P<cat_slug>\w+)/ort/(?P<place>[%-_\w\0-9]+)/$', views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/start/(?P<pickup>[%-_\w\0-9]+)/ende/(?P<return>[%-_\w\0-9]+)/$', views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/tag/(?P<day>[%-_\w\0-9]+)/$', views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/kategorie/(?P<cat_slug>\w+)/(?P<term>[%-_\w\0-9]+)/$', views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/ort/(?P<place>[%-_\w\0-9]+)/start/(?P<pickup>[%-_\w\0-9]+)/ende/(?P<return>[%-_\w\0-9]+)/radius/(?P<distance>[\d]+)km/$',
        views.search.SearchResultsView.as_view(), name='search_results'),
    url(r'^suche/ort/(?P<place>[%-_\w\0-9]+)/start/(?P<pickup>[%-_\w\0-9]+)/ende/(?P<return>[%-_\w\0-9]+)/$', views.search.SearchResultsView.as_view(), name='search_results'),

src/gearo/models/_custom_fields.py
from django.core.exceptions import ValidationError

from phonenumber_field.modelfields import PhoneNumberField
from phonenumber_field.phonenumber import to_python


class GearoPhoneNumberField(PhoneNumberField):

    default_error_messages = {
        'invalid': 'Bitte füge eine gültige Handynummer ein.',
        'required': 'Bitte gib deine Nummer an.',
    }

    def to_python(self, value):
        phone_number = to_python(value)
        if phone_number and not phone_number.is_valid():
            raise ValidationError(self.error_messages['invalid'])
        # Because of known issue with django-phonenumber-field
        # https://github.com/stefanfoulis/django-phonenumber-field/issues/136
        # we need next two lines to show '' when model field is empty (None)
        if phone_number == '+NoneNone':
            phone_number = ''
        return phone_number

src/gearo/models/advertisement_categories.py
"""
@copyright: 2016 gearo GmbH
@author: Obtrusiv Solutions UG (haftungsbeschraenkt)
@license: proprietary
"""
from django.db import models

from autoslug import AutoSlugField


class AdvertisementCategory(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150)
    meta_description = models.TextField(null=True, blank=True)
    secret_name = models.CharField(max_length=150)
    slug = AutoSlugField(populate_from='name', unique=True)
    parent = models.ForeignKey('self', null=True, blank=True)
    active = models.BooleanField(default=True)
    # "Drone and Pilot", "Studio" categories does not have pickup and return date.
    # Thus, needs to be billed for every day of rent.
    is_billed_daily = models.BooleanField(default=False)
    is_insured = models.BooleanField(default=True)
    terms_of_service = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.name

src/gearo/models/advertisement_questions.py
"""
@copyright: 2016 gearo GmbH
@author: Obtrusiv Solutions UG (haftungsbeschraenkt)
@license: proprietary
"""
from django.contrib.auth.models import User
from django.db import models

from gearo.models.advertisement import Advertisement


class AdvertisementQuestions(models.Model):
    id = models.AutoField(primary_key=True)
    ad = models.ForeignKey(Advertisement)
    questioner = models.ForeignKey(User)
    question = models.TextField()
    answer = models.TextField(max_length=200, blank=True, null=True)
    asked_date = models.DateTimeField(auto_now_add=True)
    answered_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return 'Question #%s for Ad #%s' % (self.id, self.ad_id)

src/gearo/models/attachments.py
"""
@copyright: 2016 gearo GmbH
@author: Obtrusiv Solutions UG (haftungsbeschraenkt)
@license: proprietary
"""
import os
import uuid

from django.db import models

from gearo.models.mixins import AttachmentMixin


def get_upload_path(instance, filename):
    ext = os.path.splitext(filename)[1]
    filename = "%s%s" % (uuid.uuid4(), ext)
    return os.path.join('attachments/', filename)


class Attachments(AttachmentMixin):
    ad = models.ForeignKey('gearo.Advertisement', blank=True, null=True, related_name='attachments')

    def __str__(self):
        return 'Attachment #%s for Ad #%s' % (self.id, self.ad_id)

src/gearo/models/billsystem.py
"""
@copyright: 2016 gearo GmbH
@author: Obtrusiv Solutions UG (haftungsbeschraenkt)
@license: proprietary
"""
from tempfile import NamedTemporaryFile

from django import template
from django.conf import settings
from django.contrib.auth.models import User
from django.core.files import File
from django.db import models
from django.template.loader import render_to_string

from weasyprint import CSS, HTML
from weasyprint.fonts import FontConfiguration

from gearo.models.transactions import Transactions

BILL_TYPES = (
    ("invoice", "rechnung"),
    ("payout", "auszahlung"),
    ("credit", "auszahlung-gearo")
)


class Billsystem(models.Model):
    id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=10, default="invoice", choices=BILL_TYPES)
    transaction = models.ForeignKey(Transactions, blank=True, null=True)
    count = models.IntegerField(default=0)
    creator = models.ForeignKey(User, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    invoice = models.FileField(upload_to='invoices/', blank=True, null=True)

    def lessor_billnumber(self):
        return str(self.transaction.lessor.id) + "-" + "%05d" % self.count
    
    def filename(self):
        return "%s-%s-%05d.pdf" % (self.get_type_display(),
                                   self.transaction.id, self.count)

    def render_invoice(self):
        template_context = {
            "trans": self.transaction,
            "bill": self,
            "lessor": self.transaction.lessor.gearouser,
            "lessor_user": self.transaction.lessor,
            "lessor_profile": self.transaction.lessor.profile,
            "tenant": self.transaction.applicant.gearouser,
            "tenant_user": self.transaction.applicant,
            "tenant_profile": self.transaction.applicant.profile,
            "BASE_URL": settings.BASE_URL,
        }
        c = template.Context(template_context)
        if self.transaction.lessor.gearouser.country_code == "DE":
            template_name = 'gearo/bills/invoice_lessor_de.html'
        else:
            template_name = 'gearo/bills/invoice_lessor_at.html'
        return render_to_string(template_name, c)

    def generate_invoice(self):
        tmp_pdf_file = NamedTemporaryFile()
        HTML(string=self.render_invoice()).write_pdf(
            tmp_pdf_file.name,
            stylesheets=[CSS(
                string='@page { size: A4; margin: 1.5cm }',
                font_config=FontConfiguration(),
            )],
        )
        tmp_pdf_file.seek(0)
        self.invoice.save(self.filename(), File(tmp_pdf_file))

    def __str__(self):
        return "bill %i " % self.id
    
    class Meta:
        ordering = ['-created_at']

src/gearo/models/mixins.py
import os
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from easy_thumbnails.fields import ThumbnailerImageField


def get_upload_path(instance, filename):
    ext = os.path.splitext(filename)[1]
    filename = "%s%s" % (uuid.uuid4(), ext)
    return os.path.join('attachments/', filename)


class AttachmentMixin(models.Model):
    STATUS_TEMPORARY = 1
    STATUS_ACTIVE = 2
    STATUS_INACTIVE = 3

    STATUSES = (
        (STATUS_ACTIVE, 'Temporary'),
        (STATUS_ACTIVE, 'Active'),
        (STATUS_INACTIVE, 'Inactive')
    )

    original_image = models.ImageField(upload_to=get_upload_path)
    image = ThumbnailerImageField(upload_to='attachments/', blank=True, null=True)
    status = models.IntegerField(choices=STATUSES, default=STATUS_TEMPORARY)
    updatedate = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    class Meta:
        abstract = True


class IsActiveMixin(models.Model):
    start_date = models.DateTimeField(blank=True, null=True)
    expired_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        abstract = True

    @property
    def is_active(self):
        if all([self.start_date, self.expired_date]):
            return self.start_date < timezone.now() < self.expired_date
        return True

src/gearo/models/sites.py
"""
@copyright: 2016 gearo GmbH
@author: Obtrusiv Solutions UG (haftungsbeschraenkt)
@license: proprietary
"""
from django.db import models

from autoslug import AutoSlugField


class Sites(models.Model):
    slug = AutoSlugField(populate_from='title', unique=True)
    title = models.CharField(max_length=120)
    content = models.TextField()
    template_name = models.CharField(max_length=255, editable=False, null=True, blank=True)

    def __str__(self):
        return self.title

src/gearo/templates/gearo/controllarea/addvoucher.html
{% extends "gearo/controllarea/base.html" %} {% load staticfiles %} 
{% block title %}Miete und vermiete Film- und Fotoequipment - gearo {% endblock %} 
{% block content %}
<div class="page-header">
	{% if section == "add"%}
		<h1>Rabattcode hinzufügen</h1>
	{% else %}
		<h1>Rabattcodes</h1>
	{% endif %}

	 {% if success %}
		{% if section == add%}
		<div class="alert alert-success" role="alert">Rabattcode erfolgreich hinzugefügt</div>
		{% else %}
			<div class="alert alert-success" role="alert">Rabattcode erfolgreich hinzugefügt</div>
		{% endif %}

		{% endif %}
	{% if section == "add" %}
		<form action="{% url 'addvoucherscp' %}" method="post">
			{% csrf_token %}
			{{ form  }}
			<div>
				<input type="submit" value="Submit" />
			</div>
		</form>
	{% elif section == "edit" %}
		<form action="{% url 'editvoucherscp' voucher.id %}" method="post">
			{% csrf_token %}
			{{ form  }}
			<div>
				<input type="submit" value="bearbeiten" />
			</div>
		</form>
	{% else %}
	<div class="pull-right">
		<a href="{% url 'addvoucherscp'%}"><button>Rabattcode hinzuf&uuml;gen</button></a>
	</div>
	<div>
		<table class="table" id="allvouchers">
			<thead>
				<th>ID</th>
				<th>Code</th>
				<th>Wert (%)</th>
				<th>Zugewiesener User</th>
				<th>Aktivierungen</th>
				<th>Maximale Aktivierungen</th>
				<th>Gültig ab</th>
				<th>Gültig bis</th>
				<th>bearbeiten</th>
				<th>erstellt am</th>
				<th></th>
			</thead>
			<tbody>
				{% for voucher in vouchers %}
				<tr>
					<td>{{ voucher.id }}</td>
					<td>{{ voucher.voucher|escape  }}</td>
					<td>{{ voucher.value }}</td>
					<td>{{ voucher.owner }}</td>
					<td>{{ voucher.activations }}</td>
					<td>{{ voucher.activation_limit }}</td>
					<td>{{ voucher.start_date|date:"d.m.Y" }}</td>
					<td>{{ voucher.expired_date|date:"d.m.Y" }}</td>
					<td>{{ voucher.created_at|date:"d.m.Y" }}</td>
					<td><a href="{% url 'editvoucherscp' voucher.id %}">bearbeiten</a></td>
					<td><a href="{% url 'appsvoucherscp' voucher.id %}">applications</a></td>
				</tr>
				{% endfor %}
			</tbody>
		</table>

		{% endif %}
		<script>
			$(document).ready(function() {
				$('#allvouchers').DataTable({});
				$('#id_start_date').daterangepicker({
					"singleDatePicker": true,
					autoUpdateInput: false,
					  locale: {
						  cancelLabel: 'Clear'
					  }
				});

			$('#id_start_date').on(
					'apply.daterangepicker',
					function(ev, picker) {
						$(this).val(
								picker.startDate.format('MM/DD/YYYY'));
					});
			$('#id_expired_date').daterangepicker({
				"singleDatePicker": true,
				autoUpdateInput: false,
				  locale: {
					  cancelLabel: 'Clear'
				  }
			});

			$('#id_expired_date').on(
				'apply.daterangepicker',
				function(ev, picker) {
					$(this).val(
							picker.startDate.format('MM/DD/YYYY'));
				});
			});
		</script>
	</div>
{% endblock %}

src/gearo/templates/gearo/controllarea/categorie.html
{% extends "gearo/controllarea/base.html" %} {% load staticfiles %}
{% block title %} Kategorien {% endblock %} 
{% block content %}
	<div class="page-header">
	{% if section == "add" %}
		 <h1>Kategorie hinzufügen</h1>
	{% elif section == "edit" %}
		<h1>Kategorie "{{cat.name}}" bearbeiten</h1>
	{% elif section == "delete" %}
		<h1> </h1>
	{% else %}
	  <h1>Kategorie Übersicht</h1>
	{% endif %}
	</div>
	{% if section == "add" %}
		 {% if success %}
			<div class="alert alert-success" role="alert">Kategorie erfolgreich hinzugefügt</div>
		{% endif %}
		<form action="{% url 'addadcategorie' %}" method="post">
	    	{% csrf_token %}
	    	{{ form }}
	    	<div>
	    		<input type="submit" value="Submit" />
			</div>
		</form>
	{% elif section == "edit" %}
		{% if success %}
			<div class="alert alert-success" role="alert">Kategorie erfolgreich bearbeitet</div>
		{% endif %}
		<form action="{% url 'editadcategorie' cat.id %}" method="post">
	    	{% csrf_token %}
	    	{{ form}}
	    	<div>
	    		<input type="submit" value="Submit" />
			</div>
		</form>
	{% elif section == "delete" %}
		<h1> </h1>
	{% else %}
	<div class="pull-right">
  	<a href="{% url 'addadcategorie'%}"><button> Kategorie hinzuf&uuml;gen</button></a>
	</div>
	<table class="table" id="allcat">
		<thead>
			<th>ID</th>
			<th>Name</th>
			<th>Parent</th>
			<th>bearbeiten</th>
		</thead>
		<tbody>
			{% for cat in cats %}
			<tr>
				<td>{{ cat.id }}</td>
				<td>{{ cat.name }}</td>
				<td>{{ cat.parent|default:"Main" }}
				</td>
				<td><a href="{% url 'editadcategorie' cat.id %}">bearbeiten</a></td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	<script>
		$(document).ready(function() {
			$('#allcat').DataTable({});
		});
	</script>
	{% endif %}
{% endblock %}

src/gearo/templates/gearo/controllarea/constance.html
{% extends "gearo/controllarea/base.html" %} {% load staticfiles %} 
{% block title %}Miete und vermiete Film- und Fotoequipment - gearo {% endblock %} 
{% block content %}
	<div class="page-header">
		<h1>Einstellungen anpassen</h1>
		<form action="{% url 'settings' %}" method="post">
			{% csrf_token %}
			{{ form  }}
			<div>
				<input type="submit" value="Submit" />
			</div>
		</form>
	</div>
{% endblock %}

src/gearo/templates/gearo/controllarea/dashboard-base.html
{% extends "gearo/controllarea/base.html" %}
{% load static from staticfiles %}

{% block title %}Miete und vermiete Film- und Fotoequipment - gearo {% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'gearo/css/dashboard.css' %}">
{% endblock %}

{% block submenu %}
	<div id="sidebar">
		<ul class="nav nav-pills nav-stacked">
                <li role="presentation" class="{% if active_tab == 'users_tab' %} active{% endif %}"><a href="{% url 'staffdash' %}">Number of Users</a></li>
                <li role="presentation" class="{% if active_tab == 'ads_tab' %} active{% endif %}"><a href="{% url 'staffdash-new-ads' %}">Number of Ads</a></li>
                <li role="presentation" class="{% if active_tab == 'top_ads_tab' %} active{% endif %}"><a href="{% url 'staffdash-top-ads' %}">Top Ads</a></li>
                <li role="presentation" class="{% if active_tab == 'fin_trans_tab' %} active{% endif %}"><a href="{% url 'staffdash-finished-transactions' %}">Finished Transactions</a></li>
                <li role="presentation" class="{% if active_tab == 'income_tab' %} active{% endif %}"><a href="{% url 'staffdash-income' %}">Income</a></li>
                <li role="presentation" class="{% if active_tab == 'gear_tab' %} active{% endif %}"><a href="{% url 'staffdash-gear-value' %}">Gear Value</a></li>
                <li role="presentation" class="{% if active_tab == 'stat_tab' %} active{% endif %}"><a href="{% url 'staffdash-transaction-statuses' %}">Transaction Statuses</a></li>
		</ul>
	</div>
{% endblock %}